### ISSUE TITLE
DELETE & UPDATE support 

### ISSUE THREAD

**Issue by jackpgao** [Altinity/clickhouse-mysql-data-reader#140]
As the newest version of ClickHouse has supported delete and update, will you support it too?

**Comment by sunsingerus** [comment]
Yes, the plans are to support DELETE and UPDATE operations, however, no clear implementation timeline so far

**Comment by ed-fruty** [comment]
Any update for this?
https://clickhouse.yandex/docs/en/query_language/alter/#alter-mutations

**Comment by sunsingerus** [comment]
No actual progress on this, busy with more priority tasks

**Comment by MxBird** [comment]
any update for this issues for 1 year?

**Comment by jackpgao** [comment]
Since data modification is asynchronous, this solution should not be implemented.

**Comment by MxBird** [comment]
> Since data modification is asynchronous, this solution should not be implemented.

能介绍下你们的解决方案 怎么解决数据更新跟删除的么？

**Comment by jackpgao** [comment]
没有解决。
ClickHouse的数据修改依靠的是后台的异步Merge，是不可控的，binlog通过过来，乱序执行后，数据就不一致了。

**Comment by MxBird** [comment]
> 没有解决。
> ClickHouse的数据修改依靠的是后台的异步Merge，是不可控的，binlog通过过来，乱序执行后，数据就不一致了。

能给个聊天方式么 微信或者QQ 想请教下clickhouse的相关问题

**Comment by ericchuawc** [comment]
so if the data in mysql is updated or deleted, it won't be sync to clickhouse?

**Comment by poweroftrue** [comment]
Hello @jackpgao,
Even if the data modification is asynchronous it can be very useful, we can include a warning that data update/delete will take some time or near real-time.

Even if update/delete works in the background and breaks consistency, that's already happening in other tools. 

For most use cases without this tool (using data pipeline), it already takes time to get rows by updated_at field in case data changed, deletes takes much more, and sometimes a full re-index.
