### ISSUE TITLE
document seems obsolete 

### ISSUE THREAD

**Issue by justlooks** [Altinity/clickhouse-mysql-data-reader#144]
doc says 

> clickhouse-mysql \
    --src-host=127.0.0.1 \
    --src-user=reader \
    --src-password=Qwerty1# \
    --create-table-sql-template \
    --with-create-database \
    --src-only-table=airline.ontime > create_clickhouse_table_template.sql

but when I run 
```
clickhouse-mysql: error: unrecognized arguments: --src-only-table=airline.ontime
```

**Comment by sunsingerus** [comment]
fixed
