### ISSUE TITLE
update and delete

### ISSUE THREAD

**Issue by kyle-cx91** [Altinity/clickhouse-mysql-data-reader#182]
Does the latest version support update and delete?

**Comment by Slach** [comment]
what you mean when say "update and delete"?
do you mean add\remove clickhouse nodes?
or update \ delete table data on clickhouse nodes?

for background data modification ClickHouse support MUTATIONS
https://clickhouse.tech/docs/en/sql-reference/statements/alter/#query_language_queries_alter

**Comment by Slach** [comment]
sorry, mutations don't support by clickhouse-mysql-data-reader

**Comment by kyle-cx91** [comment]
I mean,if data in MySQL is updated or deleted,
wolud it be handled by latest clickhouse-mysql-data-reader&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eugene Klimov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午3:57
收件人:&nbsp;"Altinity/clickhouse-mysql-data-reader"<clickhouse-mysql-data-reader@noreply.github.com&gt;;
抄送:&nbsp;"唐"<2410753379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Altinity/clickhouse-mysql-data-reader] update and delete (#182)





 
what you mean when say "update and delete"?
 do you mean add\remove clickhouse nodes?
 or update \ delete table data on clickhouse nodes?
 
for background data modification ClickHouse support MUTATIONS
 https://clickhouse.tech/docs/en/sql-reference/statements/alter/#query_language_queries_alter

**Comment by kyle-cx91** [comment]
thx for ur help




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eugene Klimov"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午3:58
收件人:&nbsp;"Altinity/clickhouse-mysql-data-reader"<clickhouse-mysql-data-reader@noreply.github.com&gt;;
抄送:&nbsp;"唐"<2410753379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Altinity/clickhouse-mysql-data-reader] update and delete (#182)





 
sorry, mutations don't support by clickhouse-mysql-data-reader
