### ISSUE TITLE
ImportError: cannot import name 'charset_to_encoding'

### ISSUE THREAD

**Issue by RSBianca** [Altinity/clickhouse-mysql-data-reader#183]
Hello,

use clickhouse-mysql for migrate data from mysql to clickhouse.
When we try to run migration receive errors:

ImportError: cannot import name 'charset_to_encoding'

Step to reproduce.
In mysql:

1 create database test
2 CREATE TABLE  test.testCHMysql ( test1 varchar(32) NOT NULL, test2  int(11) DEFAULT NULL);

In clickhouse:

4 create database test
5 CREATE TABLE test.testCHMysq (test1 String, test2 Int32 ) ENGINE = Distributed('{cluster}','test','testCHMysq',cityHash64( test1, test2 ));
6 CREATE TABLE test.testCHMysq ON CLUSTER test  (test1 String, test2 Int32 ) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{node}/test/testCHMysq', '{replica}') PARTITION BY test1 ORDER BY (test1, test2) ;

7 Start migration from mysql to clickhouse
clickhouse-mysql --src-server-id=1 --src-wait --src-resume --src-host=mysql  --nice-pause=1 --src-tables=test.testCHMysql --src-user=user --src-password=password --dst-host=cclickhouse-server --dst-schema=test --dst-table=testCHMysql --dst-user=user --dst-password=password

![2020-08-21_accaac](https://user-images.githubusercontent.com/70018614/90890535-d7afba80-e3c2-11ea-8555-6fe5eaa6111a.png)

 ----------- 

tried to install:

1. yum install mariadb-devel gcc python3-devel
2. pip3 install clickhouse-mysql

and tried this way:
1. pip3 install mysqlclient
2. pip3 install mysql-replication
3. pip3 install clickhouse-driver
4. pip3 install clickhouse-mysql

python version 3.6.8
CentOS Linux release 7.6.1810 (Core)

**Comment by javier-sanz** [comment]
It seems the problem is on the replication library, see https://github.com/noplay/python-mysql-replication/issues/325 .

The workaround on that thread `pipenv install pymysql~=0.9.3` worked for me.

**Comment by RSBianca** [comment]
> It seems the problem is on the replication library, see [noplay/python-mysql-replication#325](https://github.com/noplay/python-mysql-replication/issues/325) .
> 
> The workaround on that thread `pipenv install pymysql~=0.9.3` worked for me.


Yes it helped, thanks

**Comment by binbinyounimen** [comment]
或者按照这个pr进行修改也可以
https://github.com/noplay/python-mysql-replication/pull/326/files
