### ISSUE TITLE
can this tool write the event to clickhouse cluster?

### ISSUE THREAD

**Issue by yuuch** [Altinity/clickhouse-mysql-data-reader#186]
In all the example , there are always one clickhouse node , whether this tools work well on clickhouse cluster?

**Comment by sv3t0sl4v** [comment]
I did not test it with nodes and shared DAS, but interested to find out, too. What do your nodes do? Replicas? If they are replicas of each other, maybe each node should copy from it's local MySQL instance, since they are in sync anyway.

**Comment by yuuch** [comment]
yeah . the node I mentioned is  replica. But can this tools  sync  data to different shards , while not one shard(two replicas)? I would like to sync data from mysql to a cluster where there is many shards .

**Comment by lucasfcnunes** [comment]
@yuuch, why did you close the issue? Did you solve it for multiple "unreplicated" shards?
